### ISSUE TITLE
[ToDo]: V0.1.6 Iteration Plan

### ISSUE THREAD

**Issue by iofu728** [microsoft/MInference#50]
# V1.6.0 Iteration Plan

## Feature Support

- [x] Code refactors, support "attn_type", "kv_type"; #96
- [x] Resupport search pattern; #156 
- [x] Resupport chuck FFN/LN; #133 
- [x] Add SCBench codebase; #96

**Comment by iofu728** [comment]
V0.1.6 Released.
